### ISSUE TITLE
error while trying installation

### ISSUE THREAD

**Issue by Elbastu** [nagyrajmund/gesticulating_agent_unity#4]
Hello
I am trying to run your project based on the instructions you gave on Installation.md.
However I am encountering a series of errors. I would like to know your execution is made on windows or linux?
I 'm using windows 10 and I followed the same steps.
I get this error first :  "ERROR: Failed building wheel for pysptk"
but I continued the installation and I get this error when I trying main.py
![image](https://user-images.githubusercontent.com/80680772/118991759-e8a25200-b97b-11eb-86a3-ccbe7dd2ddf5.png)

Thank you for your help !

**Comment by nagyrajmund** [comment]
Hi,

I developed the project on Linux but it works on Windows as well.

I think pysptk is a dependency of the text-to-speech library. Did you install espeak/SoX?

The python error on your picture seems to be an issue with the FastText model, which is downloaded automatically on the first run. My guess is that the downloaded files got corrupted somehow, so please look for a `.word_vectors_cache` folder and delete it. You might have turn on the 'show hidden files' setting in the windows file explorer to see it; it should be somewhere around the `interface` folder. 

Also, please make sure that you have enough disk space (~10GB) for the download.

**Comment by nagyrajmund** [comment]
Hi @Allaoui-Mohamed-El-Bastu , 

did you manage to resolve your issue?

**Comment by Elbastu** [comment]
I have not yet managed to run the application. I took your comments into account. I get this error
![image](https://user-images.githubusercontent.com/80680772/119665325-2e539480-be2c-11eb-81aa-946a87e27713.png)
![image](https://user-images.githubusercontent.com/80680772/119665361-38759300-be2c-11eb-9f1c-6d2efa021b8b.png)

**Comment by Elbastu** [comment]
Hi @nagyrajmund thank you for your help ! 
I' m trying to execute the blenderbot version of the project. But unfortunately I got error (screenshot above). 
I think that the error is related to the GowTTS. Is it occurred because I don't have GPU?

**Comment by nagyrajmund** [comment]
> unfortunately I got error (screenshot above). [...] Is it occurred because I don't have GPU?

According to the error the dimensions downloaded TTS model don't exactly match what the code expects. I'm not sure how that happened, I suggest to redownload the TTS model's checkpoints _(note that you might have to delete the old ones first)_

```
cd gesticulator/interface/TTS_repo
# Download TTS model files
gdown --id 1NFsfhH8W8AgcfJ-BsL8CYAwQfZ5k4T-n -O tts_model.pth.tar
gdown --id 1IAROF3yy9qTK43vG_-R67y3Py9yYbD6t -O config.json
gdown --id 1Ty5DZdOc0F7OTGj9oJThYbL5iVu_2G0K -O vocoder_model.pth.tar
gdown --id 1Rd0R_nRCrbjEdpOwq6XwZAktvugiBvmu -O config_vocoder.json
gdown --id 11oY3Tv0kQtxK_JPgxrfesa99maVXHNxU -O scale_stats_vocoder.npy
```

**Comment by nagyrajmund** [comment]
Also, make sure that you did not make any changes to the source code in the `TTS_repo` folder.

I am fairly busy in the upcoming weeks so sadly I might not be able to try to reproduce the issue on my own computer. 

If the GlowTTS issue cannot be resolved, then you may either try the [`dialogflow` version](https://github.com/nagyrajmund/gesturebot/tree/dialogflow_demo) of the project, or temporarily replace the TTS in the `blenderbot` version as follows:

1) Remove [line 40](https://github.com/nagyrajmund/gesturebot/blob/blenderbot_demo/gesticulator/gesticulator/interface/gesture_generator_service.py#L40) and all other references to `self.tts_model` in the GestureGeneratorService

2) Store your own audio file as `Unity/Assets/ChatbotResponse.wav`.

**Comment by Elbastu** [comment]
> Also, make sure that you did not make any changes to the source code in the `TTS_repo` folder.
> 
> I am fairly busy in the upcoming weeks so sadly I might not be able to try to reproduce the issue on my own computer.
> 
> If the GlowTTS issue cannot be resolved, then you may either try the [`dialogflow` version](https://github.com/nagyrajmund/gesturebot/tree/dialogflow_demo) of the project, or temporarily replace the TTS in the `blenderbot` version as follows:
> 
>     1. Remove [line 40](https://github.com/nagyrajmund/gesturebot/blob/blenderbot_demo/gesticulator/gesticulator/interface/gesture_generator_service.py#L40) and all other references to `self.tts_model` in the GestureGeneratorService
> 
>     2. Store your own audio file as `Unity/Assets/ChatbotResponse.wav`.

I will follow your suggestions and I will let you know the results
Thank you !

**Comment by Svito-zar** [comment]
@Allaoui-Mohamed-El-Bastu , how did it go for you?

**Comment by Elbastu** [comment]
Hi @Svito-zar I'm sory for the late reply. I'm still working on it. I had left it out for a while for some reason. But I'll be working on it again for the next week. I'll let you know. thank you !

**Comment by Elbastu** [comment]
> Also, make sure that you did not make any changes to the source code in the `TTS_repo` folder.
> 
> I am fairly busy in the upcoming weeks so sadly I might not be able to try to reproduce the issue on my own computer.
> 
> If the GlowTTS issue cannot be resolved, then you may either try the [`dialogflow` version](https://github.com/nagyrajmund/gesturebot/tree/dialogflow_demo) of the project, or temporarily replace the TTS in the `blenderbot` version as follows:
> 
> 1. Remove [line 40](https://github.com/nagyrajmund/gesturebot/blob/blenderbot_demo/gesticulator/gesticulator/interface/gesture_generator_service.py#L40) and all other references to `self.tts_model` in the GestureGeneratorService
> 2. Store your own audio file as `Unity/Assets/ChatbotResponse.wav`.

Thank you very much Now it 's working ! I just had problem with dialogFlow Service. And sory for the late response.
