### ISSUE TITLE
about unity

### ISSUE THREAD

**Issue by birdflies** [nagyrajmund/gesticulating_agent_unity#5]
Hi,I am a freshman in unity. 1) How to load  "gesturebot.x86_64" file to unity?  2) do gesturebot.x86_64 support MAC system?
![Uploading image.png…]()

**Comment by birdflies** [comment]
Hi, I have solved it. Thanks very much.

**Comment by Svito-zar** [comment]
@birdflies , could you please write here how you solved your problem?
It would help others who might have this question in the future

**Comment by birdflies** [comment]
Ok.
The recommended version of unity is preferably 2020.3.16f1
1. Gesturebot.x86_64 support MAC system
2.  unzip the file "linux_release.zip" and "unity_source_code_blenderbot.zip", then put the contents of unity into blenderbot_demo path
3. remove "Newtonsoft.Json.dll"  file，it seems to be incompatible.

**Comment by Svito-zar** [comment]
Thank you @birdflies .
@nagyrajmund , would you like to update the ReadMe accordingly?

**Comment by birdflies** [comment]
Ok, i have update the ReadMe in https://github.com/birdflies/gesturebot.git patch-1 branch.
